// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHoSGwc0yYyMMNGM3drpg-5BhhpMjg8DA',
    appId: '1:653421876678:web:7181c6023a28b4e86d4ec7',
    messagingSenderId: '653421876678',
    projectId: 'eventy-pi',
    authDomain: 'eventy-pi.firebaseapp.com',
    storageBucket: 'eventy-pi.firebasestorage.app',
    measurementId: 'G-DMC1DJ6CH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXpW4wDeW-N0eHlTOGcp1iRmcER7tg9Ww',
    appId: '1:653421876678:android:a46b838dbd58a38a6d4ec7',
    messagingSenderId: '653421876678',
    projectId: 'eventy-pi',
    storageBucket: 'eventy-pi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9qseG2hIFmkeQvLwN5OehMFhQNZA7bcI',
    appId: '1:653421876678:ios:9002d676452afcfb6d4ec7',
    messagingSenderId: '653421876678',
    projectId: 'eventy-pi',
    storageBucket: 'eventy-pi.firebasestorage.app',
    iosBundleId: 'com.example.eventy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9qseG2hIFmkeQvLwN5OehMFhQNZA7bcI',
    appId: '1:653421876678:ios:9002d676452afcfb6d4ec7',
    messagingSenderId: '653421876678',
    projectId: 'eventy-pi',
    storageBucket: 'eventy-pi.firebasestorage.app',
    iosBundleId: 'com.example.eventy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHoSGwc0yYyMMNGM3drpg-5BhhpMjg8DA',
    appId: '1:653421876678:web:cf78e3c576675ffe6d4ec7',
    messagingSenderId: '653421876678',
    projectId: 'eventy-pi',
    authDomain: 'eventy-pi.firebaseapp.com',
    storageBucket: 'eventy-pi.firebasestorage.app',
    measurementId: 'G-QQXGR4S70H',
  );

}